name: 'auto release'
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  call-workflow-passing-data:
    if: github.event.pull_request.merged
    uses: fivetran-catfritz/auto-releaser/.github/workflows/auto-release.yml@main
    secrets: inherit